In [27]:
from scipy.stats import dirichlet
import numpy as np

In [52]:
test = dirichlet((20000000000, 100000000, 20000000))

In [53]:
test

In [7]:
vals = test.pdf(0.2)

IndexError: tuple index out of range

In [54]:
samples = test.rvs(size=100000)

In [55]:
samples.sum(axis=0) / samples.sum(axis=0).sum()

array([ 0.99403579,  0.00497017,  0.00099404])

In [56]:
samples[10000]

array([ 0.99403564,  0.00497016,  0.0009942 ])

In [57]:
samples[100]

array([  9.94036050e-01,   4.97007799e-03,   9.93872238e-04])

In [43]:
test.alpha

array([2, 2, 2])

In [44]:
test.alpha.dtype

dtype('int64')