In [1]:
import numpy as np
from cvxpy import *

In [5]:
# read in the data
X = []
y = []

with open('./mystery.data', 'r') as f:
    for line in f:
        info = line.strip('\n').split(',')
        X.append([float(i) for i in info[:-1]])
        y.append(float(info[-1]))

In [6]:
X = np.vstack(X)
y = np.array(y)

# test with smaller number of samples
# X = X[500:505]
# y = y[500:505]


In [8]:
print(y[:10])

[-1.  1. -1. -1. -1. -1.  1.  1. -1. -1.]


In [9]:
print(X.shape)
print(y.shape)

(1000, 4)
(1000,)


In [91]:
print(X[-1])

[ 0.05497415  0.1981697   0.83571335  0.61553188]


In [93]:
print(X[:10])
print(y[:10])

[[ 0.58224917  0.14025536  0.85577189  0.79675142]
 [ 0.54073934  0.26013019  0.67079711  0.11381718]
 [ 0.86994103  0.0868151   0.52359205  0.1588243 ]
 [ 0.26477903  0.42939734  0.29881541  0.35582812]
 [ 0.31807408  0.25728279  0.70396908  0.84775856]
 [ 0.11921454  0.29755538  0.38161088  0.5827812 ]
 [ 0.93982947  0.42485841  0.567685    0.58617767]
 [ 0.64555187  0.11920726  0.88786095  0.92583799]
 [ 0.47946322  0.49506692  0.84294929  0.57507827]
 [ 0.63931696  0.70640723  0.89879856  0.0099774 ]]
[ 1.  1. -1. -1.  1.  1. -1.  1.  1.  1.]


In [94]:
W = Variable(4)
b = Variable()
# loss = sum_entries(pos(1 - mul_elemwise(y, X*W + b)))
# prob = Problem(Minimize(loss/N))

In [95]:
constraints = []
for i in range(X.shape[0]):
    # constraints.append(y*(X[i]*W + b) >= 1)
    # print(X[i].shape)
    constraints.append(y[i]*(mul_elemwise(X[i], W) + b) >= 1)
prob = Problem(Minimize(sum_squares(W)), constraints=constraints)

In [96]:
result = prob.solve(solver=None, verbose=True)
print(result)


ECOS 2.0.4 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +8.799e-17  +3.999e+02  +6e+02  1e+00  9e-01  1e+00  1e+00    ---    ---    1  1  - |  -  - 
 1  +1.960e+03  +2.398e+04  +3e+02  5e+01  8e+01  3e+02  8e-01  0.5625  2e-01   1  1  1 |  0  0
 2  -3.345e+01  +2.006e+03  +3e+02  4e+00  6e+00  4e+02  8e-01  0.0347  9e-01   1  1  1 |  0  0
 3  -2.623e+00  +6.146e+02  +8e+01  1e+00  7e-01  4e+02  5e-01  0.6964  4e-01   1  1  1 |  0  0
 4  +1.971e+02  +3.939e+04  +1e+01  9e+00  6e+00  4e+04  4e-02  0.9890  7e-02   2  1  2 |  0  0
 5  +1.915e+04  +3.206e+06  +1e-01  8e+00  5e+00  3e+06  4e-04  0.9890  1e-04   2  1  1 |  0  0
 6  +1.749e+06  +2.915e+08  +2e-03  9e+00  5e+00  3e+08  5e-06  0.9890  1e-04   2  1  1 |  0  0
 7  +1.101e+08  +1.776e+10  +3e-05  9e+00  5e+00  2e+10  8e-08  0.9837  1e-04   2  1  1 |  0  0
 8  +2.468e+09  +3.517e+11  +1e-06  9e+00  5e+

In [16]:
print(W.value)
print(b.value)

[[-5.49099606]
 [-7.65274513]
 [ 6.8198238 ]
 [ 6.57438431]]
-0.313335851526


In [17]:
W_val = W.value
b_val = b.value

In [18]:
# print(y[1]*(np.dot(W_val.T, X[1]) + b_val))
# print(y[900]*(np.dot(W_val.T, X[900]) + b_val))
num_wrong = 0
for i in range(1000):
    value = y[i]*(np.dot(W_val.T, X[i]) + b_val)
    if value < 0:
        print(i, value)
        num_wrong += 1

14 [[-2.58513599]]
16 [[-0.59911021]]
22 [[-0.7825249]]
24 [[-0.69302857]]
30 [[-1.28294255]]
43 [[-0.21159732]]
44 [[-0.22166856]]
56 [[-0.72261761]]
59 [[-0.82942515]]
63 [[-0.17283969]]
83 [[-0.12934112]]
104 [[-1.03846832]]
109 [[-2.87409597]]
123 [[-0.12517219]]
131 [[-1.27328501]]
161 [[-0.15963988]]
167 [[-1.45621186]]
175 [[-0.50130895]]
180 [[-0.30527609]]
182 [[-0.15134203]]
187 [[-0.80573607]]
193 [[-1.24978376]]
206 [[-1.84618465]]
211 [[-0.51239139]]
225 [[-1.17359281]]
237 [[-0.11727111]]
261 [[-2.38107101]]
262 [[-1.43759552]]
281 [[-1.38689324]]
285 [[-1.53414163]]
292 [[-0.82362577]]
296 [[-0.26496019]]
298 [[-0.07535902]]
301 [[-0.6588043]]
310 [[-1.04720125]]
326 [[-1.22053804]]
329 [[-0.39357222]]
353 [[-0.00212035]]
354 [[-0.2366016]]
356 [[-0.12789858]]
366 [[-0.38345223]]
368 [[-0.14434373]]
376 [[-2.88029793]]
389 [[-0.11512087]]
398 [[-0.40597863]]
405 [[-1.86790383]]
407 [[-0.92184763]]
472 [[-1.28538751]]
486 [[-0.25954451]]
509 [[-3.03453422]]
530 [[-0.23806

In [19]:
num_wrong

96

### Original Primal SVM

In [10]:
# parameters
N = len(y)

In [11]:
W1 = Variable()
W2 = Variable()
W3 = Variable()
W4 = Variable()
b = Variable()
# loss = sum_squares(W)
loss = W1**2 + W2**2 + W3**2 + W4**2

In [12]:
constraints = []
for i in range(N):
    # constraints.append(y[i] * (W.T*X[i] + b) >= 1)
    # mul_elemwise(Y, X*beta - v)
    if y[i] > 0:
        forward = W1*X[i][0] + W2*X[i][1] + W3*X[i][2] + W4*X[i][3] + b
    else:
        forward = -W1*X[i][0] - W2*X[i][1] - W3*X[i][2] - W4*X[i][3] - b
    constraints.append(forward >= 1.0)

In [13]:
print(constraints[1])
print(constraints[4])
print(len(constraints))

1.0 <= 0.905791937 * var0 + 0.355073652 * var1 + 0.892267188 * var2 + 0.31906782 * var3 + var4
1.0 <= 0.632359246 * -var0 + -0.652451073 * var1 + -0.225067882 * var2 + -0.413183359 * var3 + -var4
1000


In [14]:
objective = Minimize(loss)
prob = Problem(objective, constraints)

In [15]:
result = prob.solve(solver=None, verbose=True)
print(result)


ECOS 2.0.4 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +0.000e+00  +9.988e+02  +2e+03  8e-01  6e+00  1e+00  2e+00    ---    ---    1  1  - |  -  - 
 1  +3.616e+03  +5.849e+04  +1e+03  4e+01  5e+02  4e+02  1e+00  0.5677  2e-01   1  1  1 |  0  0
 2  -2.077e+01  +3.002e+03  +1e+03  2e+00  2e+01  4e+02  1e+00  0.0652  9e-01   1  1  1 |  0  0
 3  +1.054e+01  +2.743e+03  +1e+03  2e+00  2e+01  4e+02  1e+00  0.0899  7e-01   2  1  2 |  0  0
 4  +1.092e+02  +2.894e+03  +9e+02  2e+00  1e+01  8e+02  1e+00  0.4449  6e-01   2  1  1 |  0  0
 5  +1.389e+03  +1.757e+04  +3e+02  4e+00  7e+00  1e+04  3e-01  0.9890  3e-01   2  1  1 |  0  0
 6  +9.814e+03  +1.221e+05  +4e+01  4e+00  4e+00  1e+05  5e-02  0.9890  1e-01   2  1  1 |  0  0
 7  +8.443e+05  +1.038e+07  +5e-01  4e+00  4e+00  1e+07  5e-04  0.9890  1e-04   2  1  1 |  0  0
 8  +7.394e+07  +9.049e+08  +5e-03  4e+00  4e+

In [16]:
print(W1.value)
print(W2.value)
print(W3.value)
print(W4.value)
print(b.value)

None
None
None
None
None


### Using Perceptron class from sklearn

In [25]:
from sklearn.linear_model import Perceptron 

In [26]:
clf = Perceptron()
clf.fit(X,y)

/home/trimcao/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


Perceptron(alpha=0.0001, class_weight=None, eta0=1.0, fit_intercept=True,
      max_iter=5, n_iter=None, n_jobs=1, penalty=None, random_state=0,
      shuffle=True, tol=None, verbose=0, warm_start=False)

In [27]:
preds = clf.predict(X)
print(np.mean(preds == y))

0.907


### Using Perceptron algorithm

In [38]:
# parameters
N = len(y)
learning_rate = 0.0001

In [39]:
def f(W, b, X):
    """
    function f as mentioned in the lecture
    """
    return W.dot(X) + b

In [40]:
def predict(W, b, X):
    """
    Perceptron prediction.
    X is an array of samples (not just one sample).
    """
    pred = X.dot(W) + b
    # change predictions to 1 and -1
    pred[pred > 0] = 1
    pred[pred <= 0] = -1
    return pred

In [41]:
def accuracy(y_pred, y_truth):
    """
    Compute accuracy.
    """
    return np.mean(y_pred == y_truth)

In [42]:
W = np.zeros(4) # initial weights
b = 0 # initial bias
highest_acc = 0.
# (sub)gradient descent
for epoch in range(100001):
    # check accuracy
    pred = predict(W, b, X)
    acc = accuracy(pred, y)
    if acc > highest_acc:
        highest_acc = acc
    # print data
    if epoch % 1000 == 0:
        print('Iteration: ', epoch)
        print(W)
        print(b)
        print('accuracy:', acc)
        print('highest accuracy:', highest_acc)
        print()
    if (acc == 1.0):
        break
    
    # train using gradient descent
    for i in range(N):
        if -y[i]*f(W, b, X[i]) >= 0:
            W += learning_rate * y[i]*X[i]
            b += learning_rate * y[i]



Iteration:  0
[ 0.  0.  0.  0.]
0
accuracy: 0.5
highest accuracy: 0.5

Iteration:  1000
[-0.00182475 -0.00242806 -0.00202533 -0.00271714]
0.004
accuracy: 0.762
highest accuracy: 0.864

Iteration:  2000
[-0.00216548 -0.00260028 -0.00222569 -0.00304159]
0.0044
accuracy: 0.739
highest accuracy: 0.866

Iteration:  3000
[-0.00212199 -0.00262686 -0.00216561 -0.0029454 ]
0.0045
accuracy: 0.83
highest accuracy: 0.866

Iteration:  4000
[-0.00217471 -0.00269531 -0.00215778 -0.00308234]
0.0045
accuracy: 0.761
highest accuracy: 0.867

Iteration:  5000
[-0.00221221 -0.00261057 -0.00223437 -0.00307445]
0.0045
accuracy: 0.758
highest accuracy: 0.867

Iteration:  6000
[-0.00211945 -0.00273477 -0.00222697 -0.00312237]
0.0045
accuracy: 0.741
highest accuracy: 0.867

Iteration:  7000
[-0.00214691 -0.00274915 -0.00221418 -0.00310676]
0.0045
accuracy: 0.738
highest accuracy: 0.867



KeyboardInterrupt: 

### SVM from Scikit-Learn

In [32]:
from sklearn import svm
clf = svm.LinearSVC(C=1.0)
clf.fit(X,y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [33]:
W_val = clf.coef_[0]
b_val = clf.intercept_[0]

In [34]:
preds = clf.predict(X)
print(np.mean(preds == y))

0.903


### CVXPY simple example

In [ ]:
# test cvxpy
M = Variable()
N = Variable()
loss = 0.5*M**2 + 3*M + 4*N
objective = Minimize(loss)

In [ ]:
constraints = []
constraints.append(M >= 0)
constraints.append(N >= 0)
constraints.append(M + 3*N >= 15)
constraints.append(2*M + 5*N <= 100)
constraints.append(3*M + 4*N <= 80)

In [ ]:
prob = Problem(objective, constraints)
result = prob.solve(verbose=True)

In [ ]:
M.value

In [ ]:
N.value

In [ ]:
print(result)

### CVXOPT

In [167]:
from cvxopt import matrix, solvers
Q = 2*matrix([ [2, .5], [.5, 1] ])
p = matrix([1.0, 1.0])
G = matrix([[-1.0,0.0],[0.0,-1.0]])
h = matrix([0.0,0.0])
A = matrix([1.0, 1.0], (1,2))
b = matrix(1.0)
sol=solvers.qp(Q, p, G, h, A, b)

     pcost       dcost       gap    pres   dres
 0:  1.8889e+00  7.7778e-01  1e+00  3e-16  2e+00
 1:  1.8769e+00  1.8320e+00  4e-02  2e-16  6e-02
 2:  1.8750e+00  1.8739e+00  1e-03  2e-16  5e-04
 3:  1.8750e+00  1.8750e+00  1e-05  6e-17  5e-06
 4:  1.8750e+00  1.8750e+00  1e-07  2e-16  5e-08
Optimal solution found.


In [168]:
print(sol['x'])

[ 2.50e-01]
[ 7.50e-01]



### Test on Perceptron data

In [22]:
# read in the data
X = []
y = []

with open('./perceptron.data', 'r') as f:
    for line in f:
        info = line.strip('\n').split(',')
        X.append([int(i) for i in info[:4]])
        y.append(int(info[4]))
# make the numpy arrays
X = np.vstack(X)
y = np.array(y)
# parameters
N = len(y)

In [23]:
W1 = Variable()
W2 = Variable()
W3 = Variable()
W4 = Variable()
b = Variable()
# loss = sum_squares(W)
loss = W1**2 + W2**2 + W3**2 + W4**2

In [24]:
constraints = []
for i in range(N):
    # constraints.append(y[i] * (W.T*X[i] + b) >= 1)
    # mul_elemwise(Y, X*beta - v)
    if y[i] > 0:
        forward = W1*X[i][0] + W2*X[i][1] + W3*X[i][2] + W4*X[i][3] + b
    else:
        forward = -W1*X[i][0] - W2*X[i][1] - W3*X[i][2] - W4*X[i][3] - b
    constraints.append(forward >= 1.0)

In [25]:
objective = Minimize(loss)
prob = Problem(objective, constraints)

In [31]:
result = prob.solve()
print(result)

33.31954778154782


In [27]:
print(W1.value)
print(W2.value)
print(W3.value)
print(W4.value)
print(b.value)

2.74534161271
-2.16149068143
4.45962732568
-1.10559006117
0.962732918452


In [1]:
# test the margin
num_wrong = 0
for i in range(N):
    value = y[i]*(W1.value*X[i][0] + W2.value*X[i][1] +
                  W3.value*X[i][2] + W4.value*X[i][3] + b.value)
    if value < .99:
        print(i, value)
        num_wrong += 1 
print(num_wrong)

NameError: name 'N' is not defined